### ISSUE TITLE
Can't assembly 

### ISSUE THREAD

**Issue by shaoshixiong** [Klaykap/CelerOS#2]
After I modify your code, CORB and rirb work normally. Monitoring sdlpib is changing constantly indicates that the stream works normally. In VBox, it can emit a slight current sound, but the wav data set does not reach the expected effect

**Comment by Klaykap** [comment]
Sorry, I can not say anything without seeing your actual code.

**Comment by shaoshixiong** [comment]
//LIGHTNINGOS

uint32_t corb_pointer = 0;

struct hda_buffers_t
{
	uint64_t address;
	uint32_t lenght;
	uint32_t interrupt;
} __attribute__((aligned(256))) hda_buffers[256];
void hda_outb(uint32_t offset, uint8_t value)
{
	uint8_t *mem = (uint8_t *)(hda_base + offset);
	mem[0] = value;
}

void hda_outw(uint32_t offset, uint16_t value)
{
	uint16_t *mem = (uint16_t *)(hda_base + offset);
	mem[0] = value;
}

void hda_outl(uint32_t offset, uint32_t value)
{
	uint32_t *mem = (uint32_t *)(hda_base + offset);
	mem[0] = value;
}

uint8_t hda_inb(uint32_t offset)
{
	uint8_t *mem = (uint8_t *)(hda_base + offset);
	return (mem[0]);
}

uint16_t hda_inw(uint32_t offset)
{
	uint16_t *mem = (uint16_t *)(hda_base + offset);
	return (mem[0]);
}

uint32_t hda_inl(uint32_t offset)
{
	uint32_t *mem = (uint32_t *)(hda_base + offset);
	return (mem[0]);
}

void corb_write_command(uint32_t cad, uint32_t nid, uint32_t verb, uint32_t command)
{
	uint32_t *corb = (uint32_t *)0x00070000;

	corb[corb_pointer] = 0x000F0004; //( (cad << 28) | (nid << 20) | (verb << 8) | (command) );

	corb_pointer++;
}


void showinfo(void)
{
	p("GCAP:"); //–全局能力.................................................。 .............. 28
	ph(hda_inw(0x00));
	// p("VMIN:"); //–次要版本.................................................。 ....................... 29
	// ph(hda_inb(0x02));
	// p("VMAJ:"); //–主要版本.................................... ....................... 29
	// ph(hda_inb(0x03));
	// p("OUTPAY:"); //–输出有效负载能力............................................... 29
	// ph(hda_inw(0x04));
	// p("INPAY:"); //–输入有效负载能力....................................... ...... 30
	// ph(hda_inw(0x06));
	// p("GCTL:"); //–全局控制................................... ...................... 30
	// ph(hda_inl(0x08));
	// p("WAKEEN:"); //–唤醒使能...................................。 ................. 31
	// ph(hda_inw(0x0C));
	// p("STATESTS:"); //–状态更改状态.................................. ... 32
	// ph(hda_inw(0x0E));
	// p("GSTS:"); //–全局状态................................... ....................... 32
	// ph(hda_inw(0x10));
	// p("OUTSTRMPAY:");// –输出流有效负载能力................ 32
	//bbbbbbbbbbbbbbbbbb
	// ph(hda_inw(0x18));
	// p("INSTRMPAY:");// –输入流有效负载能力............................... 33
	// ph(hda_inw(0x1A));
	// p("INTCT:");//L –中断控制:");//................................... ................ 34
	// ph(hda_inl(0x20));
	// p("INTSTS:");// –中断状态.................................................。 .................. 35
	// ph(hda_inl(0x24));
	// p("wwclk:");//.................................................. .................................... 35
	// ph(hda_inl(0x30));
	p("SSYNC:"); // –流同步..................................... .... 36
	ph(hda_inl(0x38));
	// p("CORB:");//低位基地址.................................. .............. 36
	// ph(hda_inl(0x40));
	// p("CORBUBASE:");// – CORB高基地址.................................... 36
	// ph(hda_inl(0x44));
	// p("CORBWP:");// – CORB写指针.......................................... ....... 37
	// ph(hda_inw(0x48));
	// p("CORBRP:");// – CORB读指针................................................. ....... 37
	// ph(hda_inw(0x4A));
	// p("CORBCTL:");// – CORB控制................................... .............. 37
	// ph(hda_inb(0x4C));
	// p("CORBSTS:");// – CORB状态...................................。 ............... 38
	// ph(hda_inb(0x4D));
	// p("CORBSIZE:");// – CORB Size..................................。 ................. 38
	// ph(hda_inb(0x4E));
	// p("RIRBLBASE:");// – RIRB低位基址................................ 39
	// ph(hda_inl(0x50));
	// p("RIRBUBASE:");// – RIRB高位基址............................... 39
	// ph(hda_inl(0x54));
	// p("RIRBWP:");// – RIRB写指针................................................... ...... 39
	// ph(hda_inw(0x58));
	// p("RINTCNT:");// –响应中断计数.............................................. 40
	// ph(hda_inw(0x5A));
	//aaaaaaaaaa
	// p("RIRBCTL:");// – RIRB控制................................... ................. 40
	// ph(hda_inb(0x5C));
	// p("RIRBSTS:");// – RIRB状态................................... .................. 41
	// ph(hda_inb(0x5D));
	// p("RIRBSIZE:");// – RIRB Size..................................。 ..................... 41
	// ph(hda_inb(0x5E));
	p("DPLBASE:"); // – DMA位置低位基址.................... 42
	ph(hda_inl(0x70));
	p("DPUBASE:"); // – DMA位置高位基址................................... 43
	ph(hda_inl(0x74));
	p("SDnCTL:"); // –输入/输出/双向流描述符n
	ph(hda_inl(0x80 + 0x80));
	p("SD0STS:"); // –输入/输出/双向流描述符n
	ph(hda_inb(0x83 + 0x80));
	p("SDnLPIB:"); // –输入/输出/双向流描述符n
	ph(hda_inl(0x84 + 0x80));
	p("SDnCBL:"); // –输入/输出/双向流描述符n
	ph(hda_inl(0x88 + 0x80));
	p("ISDnLVI:"); // –输入/输出/双向流描述符n
	ph(hda_inw(0x8C + 0x80));
	p("SDnFIFOS:"); // –输入/输出/双向流描述符n
	ph(hda_inw(0x90 + 0x80));
	p("SDnFMT:"); // –输入/输出/双向流描述符n
	ph(hda_inw(0x92 + 0x80));
	p("SDnBDPL:"); // –输入/输出/双向流描述符n
	ph(hda_inl(0x98 + 0x80));
	p("SDnBDPU:"); // –输入/输出/双向流描述符n
	ph(hda_inl(0x9C + 0x80));
	// p("WALCLKA:");// –壁钟计数器别名................................... 49
	// ph(hda_inl(0x2030));
}
void hda(void)
{
	uint32_t corbaddress = 0x00070000;
	uint32_t rirbaddress = 0x00060000;
	uint32_t dmaaddress = 0x00080000;
	uint32_t wavaddress = 0x00090000;
	 
	hda_outl(0x40, corbaddress);
	hda_outl(0x50, rirbaddress);
	hda_outl(0x44, 0x00000000);
	hda_outl(0x54, 0x00000000);
	hda_outl(0x20, 0x00000000);
	uint32_t *corb = (uint32_t *)corbaddress;
	uint64_t *rirb = (uint64_t *)rirbaddress;

	corb[0] = 0x000f0004;
	corb[1] = 0x00170500; //   set afg powerstate to D0
	corb[2] = 0x00570500; //	 set DAC powerstate to D0
	corb[3] = 0x00f70500; //	 set speaker-pin powerstate to D0
	corb[4] = 0x00a70500; //	 set hp-pin	powerstate to D0

	corb[5] = 0x00524011; //	 set DAC format
	corb[6] = 0x00570610; //	 set DAC stream id and channel

	corb[7] = 0x0053b07F; //	 set DAC unmute

	corb[8] = 0x00f3b07f;  //	 set speaker-pin unmute
	corb[9] = 0x00a3b07f;  //	 set speaker-pin unmute
	corb[10] = 0x0013b07f; //	 set speaker-pin unmute
	corb[11] = 0x00f70cff;
	corb[12] = 0x00570cff;
	corb[13] = 0x00a707ff; //	 set hp-pin open

	// 	corb[0]=0x00CF1c00;
	// 	ph(corb[0]);
	// 	corb[1]=0x00FF1c00;
	// 	ph(corb[1]);
	// 	corb[2]=0x01AF1c00;
	// 	ph(corb[2]);
	// 	corb[3]=0x00a70cFF;
	// 	ph(corb[3]);
	// 	corb[4]=0x00570CFF;
	// 	ph(corb[4]);
	// 	corb[5]=0x010F0100;
	// 	ph(corb[5]);
	// 	corb[6]=0x00570500; //set ADC D0
	// 	ph(corb[6]);
	// 	corb[7]=0x00570611;
	// 	ph(corb[7]);
	// 	corb[8]=0x0053000D;
	// 	ph(corb[8]);
	// 	corb[9]=0x00870500; //set ADC D0
	// 	ph(corb[9]);
	// 	corb[10]=0x00870611;
	// 	ph(corb[10]);
	// 	corb[11]=0x0083000D;
	// 	ph(corb[11]);
	// 	corb[12]=0x00f70500; //set ADC D0
	// 	ph(corb[12]);
	// 	corb[13]=0x00f70611;
	// 	ph(corb[13]);
	// 	corb[14]=0x00f3000D;
	// 	ph(corb[14]);
	// 	corb[15]=0x01a70500; //set ADC D0
	// 	ph(corb[15]);
	// 	corb[16]=0x01a70611;
	// 	ph(corb[16]);
	// 	corb[17]=0x01a3000D;
	// 	ph(corb[17]);
	// 	corb[18]=0x00572dFF;
	// 	ph(corb[18]);
	// 	corb[19]=0x00F707ff;//open speaker
	// 	ph(corb[19]);
	// 	corb[20]=0x005707ff;//open DAC
	// 	ph(corb[20]);
	// 	corb[21]=0x00A707ff;//open hp
	// 	ph(corb[21]);
	// corb[22]=0x012f0200;
	// 	ph(corb[22]);

	//================
	// corb[0] = 0x000f0004;
	// corb[1] = 0x00170500; //   set afg powerstate to D0
	// corb[2] = 0x00570500; //	 set DAC powerstate to D0
	// corb[3] = 0x00f70500; //	 set speaker-pin powerstate to D0
	// corb[4] = 0x00a70500; //	 set hp-pin	powerstate to D0

	// corb[5] = 0x00524011; //	 set DAC format
	// corb[6] = 0x00570610; //	 set DAC stream id and channel

	// corb[7] = 0x0053b07F; //	 set DAC unmute

	// corb[8] = 0x00f3b07f; //	 set speaker-pin unmute
	// corb[9] = 0x00a707ff; //	 set hp-pin open
	hda_outw(0x48, 0x20);
	uint16_t pus = 0x8000;
	hda_outw(0x4a, pus);
	for (int i = 0; i < 0xff; i++)
	{
	}
	while (hda_inw(0x4a) == 0)
	{
	}
	for (int i = 0; i < 0xff; i++)
	{
	}
	hda_outw(0x4a, 0x00);
	for (int i = 0; i < 0xff; i++)
	{
	}
	while (hda_inw(0x4a) != 0)
	{
	}
	for (int i = 0; i < 0xff; i++)
	{
	}
	hda_outw(0x58, pus);
	uint8_t res = hda_inb(0x5c);
	res = res | 2;
	res = res & 250;
	hda_outb(0x5c, res);

	uint8_t res2 = hda_inb(0x4c);
	res2 = res2 | 2;
	res2 = res2 & 254;
	hda_outb(0x4c, res2);
	ph(hda_inw(0x4a));
	ph(hda_inw(0x58));

	for (int i = 0; i < 0x20; i++)
	{
		//ph(rirb[i]); //0x001f0004 can respond to the result normally
	}
	hda_outb(0x5c, 0x00);
	hda_outb(0x4c, 0x00);
	 

	hda_outl(0x38, 0x00000000 & 0xffffffff);
 
	uint32_t *wav = (uint32_t *)wavaddress;
	for (int i = 0; i < 0x70; i++)
	{
		wav[i * 4] = 0xe0000000 + 0x800 * i;	//Playing video data as sound data, expecting to play noise
		wav[i * 4 + 1] = 0x00000000;
		wav[i * 4 + 2] = 0x800;
		wav[i * 4 + 3] = 0x0;
	}
	 

	hda_outl(0x84 + 0x80, 0x00);
	hda_outl(0x88 + 0x80, 0x800 * 0x70);
	hda_outw(0x8C + 0x80, 0x6f); //LVT
	hda_outw(0x92 + 0x80, 0x4011);
	hda_outl(0x98 + 0x80, wavaddress & 0xffffffff);
	hda_outl(0x9C + 0x80, 0x00000000 & 0xffffffff);
	hda_outl(0x70, (dmaaddress & 0xffffffff) | 0x01);
	hda_outl(0x74, 0x00000000 & 0xffffffff);
	ph((uint32_t)(&hda_buffers));

	hda_outl(0x80 + 0x80, 0x0014001E & 0xffffffff); //
	ph(hda_inl(0x80 + 0x80));
	p("aaaa");
	while (1)
	{
		for (int i = 0; i < 0x1fffffff; i++)
			;
		ph(hda_inl(0x84 + 0x80));  //The change of SDLPIB indicates that the flow is normal
	}
	ph(hda_inb(0x83 + 0x80));
	showinfo();
	 
	hda_outl(0x38, 0x1 & 0xffffffff);
	while (1)
	{
	}

	 
}

**Comment by Klaykap** [comment]
Well, base problem is that stream on ports 0x80-0x100 is input stream so you can not send wav data through it. But there are more important things.

1) HDA driver must contain these points:
 - At first turn SC(sound card) from reset state - write 0x1 to GCTL port
 - Set up interrupts
 - Set up CORB RIRB interface
 - Found all widgets whose are connected to SC
 - Sort them to lists
 - Choose one Audio Output widget you want to use(and also pin) and set it
 - Now is SC ready to use

2) Now, when you want to play some sound:
 - You must use some output stream. Every stream occupies 0x20 in port numbers. First input stream has number 0x80. So you can read number of Input streams from Global Capabilites register and calculate 0x80+(0x20*NumOfInputStreams) Virtualbox have four input streams so first output stream has port number 0x100
 - Turn stream off
 - Modify buffer entries
 - Set buffer memory position to stream
 - Set number of buffer entries
 - Set length of transferring sound data
 - Set format of sound data
 - Turn stream on
 - When you turning stream on, you set stream number, so you must be sure that Audio Output widget is programmed to capture same number of stream e.g. when you turn output stream with outl(0x100, 0x00140002) you must program widget to capture stream 1

3) You work with memory below 0x100000. It is not enough. You need much more memory for sound data so I suggest you to move pointer up to 0x100000.

4) Using while(xyz) {} is problematic because it can cause forever handle easily. You can program PIT timer and wait only for some time like 50 microseconds. If nothing change after it, you know that something is wrong and exit driver with error and not get forever stuck.

Hope this help. These are many things and I do not know with what are you familiar, so feel free to ask anything.

**Comment by shaoshixiong** [comment]
Can I modify this code until VBox can make a loud sound?

**Comment by shaoshixiong** [comment]
Reread The value of 0×100 becomes 0 × 20100002 instead of 0 × 0014002

**Comment by shaoshixiong** [comment]
I managed to play an obvious noise on my physical machine.

https://forum.osdev.org/viewtopic.php?f=1&t=32517&hilit=HDA

Write 0x1 to the reset stream of 0x100, clear the 0-2 bits of PCI register tcsel, and the sound comes out immediately

**Comment by Klaykap** [comment]
This should not be the way how it work, but if it work, all is good :) . For question about loud sound, every amplifier have another max value, so value 0x7F probably is not right. You must read max value by verb 0xF00 command 0x12 and from result mask first byte - it is max value from amplifier.
